Repository cloudposse-examples/app-on-ecs, pull requests merged in 2024-03, with the labels that each got.

#25 feat: Github Checks and Release Drafter
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
  .github/configs/environment.yaml
  .github/labeler.yaml
  .github/renovate.json
  .github/workflows/ecspresso-feature-branch.yml
  .github/workflows/ecspresso-hotfix-branch.yml
  .github/workflows/ecspresso-hotfix-mixin.yml
  .github/workflows/ecspresso-hotfix-release.yml
  .github/workflows/ecspresso-main-branch.yml
  .github/workflows/ecspresso-release.yml
  .github/workflows/ecspresso-rollback.yml
  .github/workflows/feature-branch.yml
  .github/workflows/hotfix-branch.yaml
  .github/workflows/hotfix-enabled.yaml
  .github/workflows/hotfix-release.yaml
  .github/workflows/labeler.yaml
  .github/workflows/main-branch.yaml
  .github/workflows/release.yaml
  .github/workflows/validate.yml
  .github/workflows/workflow-cd-preview-ecspresso.yml
  .github/workflows/workflow-controller-draft-release.yml
  .github/workflows/workflow-controller-hotfix-reintegrate.yml
  .github/workflows/workflow-controller-hotfix-release-branch.yml
  renovate.json
Labels: automation

#27 Allow Environment Info from another Org
  .github/configs/environment.yaml
  .github/workflows/ecspresso-feature-branch.yml
  .github/workflows/ecspresso-hotfix-branch.yml
  .github/workflows/ecspresso-hotfix-release.yml
  .github/workflows/ecspresso-main-branch.yml
  .github/workflows/ecspresso-release.yml
  .github/workflows/ecspresso-rollback.yml
  .github/workflows/feature-branch.yml
  .github/workflows/hotfix-branch.yaml
  .github/workflows/hotfix-release.yaml
  .github/workflows/main-branch.yaml
  .github/workflows/release.yaml
  .github/workflows/rollback.yaml
  .github/workflows/workflow-cd-ecspresso.yml
  .github/workflows/workflow-cd-preview-ecspresso.yml
Labels: deploy/qa1, automation

#28 update description
  README.md
  README.yaml
Labels: docs
